# Generated by Django 3.1.4 on 2020-12-18 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_auto_20201218_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logistic.state', verbose_name='Unidade Federativa'),
            preserve_default=False,
        ),
    ]
