# Generated by Django 3.1.4 on 2020-12-19 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0004_auto_20201218_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthcenter',
            old_name='razao_social',
            new_name='name',
        ),
    ]
