version: "3"

services:

  web:
    build: .
    container_name: lais_raphael_fontes_python
    ports:
      - 8010:8010
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      EMAIL_RECIPIENT: ${EMAIL_RECIPIENT}
    depends_on:
      - postgres

  postgres:
    image: postgres:12.0-alpine
    container_name: lais_raphael_fontes_postgres
    ports:
      - 5433:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: