# Generated by Django 3.1.4 on 2020-12-18 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vaccination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Observações')),
                ('status', models.CharField(choices=[('E', 'Encaminhado'), ('R', 'Remarcado'), ('P', 'Aprovado'), ('D', 'Desistido')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em:')),
                ('vaccine', models.ManyToManyField(to='vaccination.Vaccine', verbose_name='Vacina')),
            ],
            options={
                'verbose_name': 'Evento',
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em:')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scheduling.event', verbose_name='Agendamento')),
                ('vaccines', models.ManyToManyField(to='vaccination.Vaccine', verbose_name='Vacina')),
            ],
            options={
                'verbose_name': 'Vacinação',
                'verbose_name_plural': 'Vacinações',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Observações')),
                ('status', models.CharField(choices=[('E', 'Encaminhado'), ('R', 'Remarcado'), ('P', 'Aprovado'), ('D', 'Desistido')], max_length=1)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em:')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em:')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Evento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
