# Generated by Django 3.1.4 on 2020-12-18 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='when',
            field=models.DateField(blank=True, null=True, verbose_name='Quando rebeceu a vacina?'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scheduling.event', verbose_name='Agendamento'),
        ),
    ]
