# Generated by Django 3.1.4 on 2020-12-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_auto_20201219_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
