# Generated by Django 3.1.4 on 2020-12-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='age',
            field=models.CharField(choices=[('D', 'Dia'), ('M', 'Mês'), ('Y', 'Ano')], default=1, max_length=1, verbose_name='Idade em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccine',
            name='age_max',
            field=models.CharField(max_length=3, null=True, verbose_name='Idade máxima'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='age_min',
            field=models.CharField(default=1, max_length=3, verbose_name='Idade mínima'),
            preserve_default=False,
        ),
    ]
