# Generated by Django 3.1.4 on 2020-12-18 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0004_auto_20201218_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='age',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='age_max',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='age_min',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='reinforcement',
        ),
        migrations.CreateModel(
            name='Reinforcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('D', 'Dia'), ('M', 'Mês'), ('Y', 'Ano')], max_length=1, verbose_name='Idade em')),
                ('age_min', models.CharField(max_length=3, verbose_name='Idade mínima')),
                ('age_max', models.CharField(max_length=3, null=True, verbose_name='Idade máxima')),
                ('vaccine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccination.vaccine', verbose_name='Vacina')),
            ],
            options={
                'verbose_name': 'Reforço',
            },
        ),
    ]
